#!/usr/bin/env tsx
/**
 * Generates docs/ai-champion-roadmap.md from data/roadmap.json
 * Run: npx tsx tools/generate-docs.ts
 */

import { readFileSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');

const roadmap = JSON.parse(readFileSync(join(root, 'data', 'roadmap.json'), 'utf-8'));

function toolTag(tools: string[]): string {
  if (tools.includes('all')) return '';
  if (tools.length === 1) {
    const labels: Record<string, string> = { claude: 'Claude', gemini: 'Gemini', copilot: 'Copilot' };
    return ` \`[${labels[tools[0]] || tools[0]}]\``;
  }
  const labels: Record<string, string> = { claude: 'Claude', gemini: 'Gemini', copilot: 'Copilot' };
  return ` \`[${tools.map(t => labels[t] || t).join('+')}]\``;
}

const lines: string[] = [];

lines.push(`# ${roadmap.meta.title}`);
lines.push('');
lines.push(`> ${roadmap.meta.description}`);
lines.push('');
lines.push('> Generated from `data/roadmap.json`. Do not edit this file directly.');
lines.push('');
lines.push('---');
lines.push('');
lines.push('### Tool legend');
lines.push('Items are tagged where support differs. Untagged items apply to all three tools.');
lines.push('');
lines.push('| Tag | Meaning |');
lines.push('|---|---|');
lines.push('| `[Claude]` | Claude Code only |');
lines.push('| `[Gemini]` | Gemini CLI only |');
lines.push('| `[Copilot]` | GitHub Copilot CLI only |');
lines.push('| `[Claude+Gemini]` | Not available for Copilot CLI |');
lines.push('');
lines.push('---');
lines.push('');

for (const level of roadmap.levels) {
  const isAppendix = level.type === 'appendix';
  const heading = isAppendix ? level.title : `Level ${level.number} — ${level.title}`;
  lines.push(`## ${heading}`);
  lines.push(`> Goal: ${level.goal}`);
  lines.push('');

  for (const section of level.sections) {
    if (section.title) {
      lines.push(`### ${section.title}`);
      lines.push('');
    }

    for (const item of section.items) {
      const tag = toolTag(item.tools);
      const optional = item.optional ? ' *(optional)*' : '';
      const displayText = item.label ?? item.text;
      lines.push(`- [ ] ${displayText}${tag}${optional}`);
      if (item.why) {
        lines.push(`  > ${item.why}`);
        lines.push('');
      }
      if (item.detail) {
        lines.push(`  ${item.detail}`);
        lines.push('');
      }
      if (item.code) {
        lines.push(`  \`\`\`${item.code.lang}`);
        lines.push(`  ${item.code.content.split('\n').join('\n  ')}`);
        lines.push('  ```');
        lines.push('');
      }
      if (item.links && item.links.length > 0) {
        for (const link of item.links) {
          lines.push(`  - [${link.label}](${link.url})`);
        }
        lines.push('');
      }
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('');
}

const output = lines.join('\n');
const outPath = join(root, 'docs', 'ai-champion-roadmap.md');
writeFileSync(outPath, output, 'utf-8');
console.log(`Generated: ${outPath}`);
